### PR TITLE
Buck build support

### PR DESCRIPTION
**Pull request by njlr**
This PR adds support for builds using [Buck](https://buckbuild.com/).

To build with Buck:

```bash=
buck build :glm
```

To run the tests:

```bash=
buck run test/core:core_force_pure
buck run test/core:core_force_unrestricted_gentype
# etc... 
```

The existing CMake build is unchanged; the two can coexist peacefully 😊

### CODE REVIEW

**Comment by Groovounet** [comment]
Ermm, does it really belong to GLM repository?

Thanks,
Christophe

**Comment by njlr** [comment]
Yes, by merging this PR users of Buck will be able to easily integrate GLM into their projects.

**Comment by Groovounet** [comment]
Ermmm, why not a separated repository? The only use for the build system in GLM is the unit tests, multiple  build systems for that... I think I would need to stronger case to justify it.

**Comment by njlr** [comment]
It is not only about building the code, although I did write Buck files for the tests if people want to run them. The advantage of having a Buck file is that it describes which header files make up the library. The format is human and machine readable. This description makes it is easier to integrate into another project because Buck will wire-together the include paths in an intelligent way. 

I have my own fork here (https://github.com/njlr/glm/tree/improvement/buck-build), but I think people would prefer to depend on the official repository to ensure that they have up-to-date code.

**Comment by nikhedonia** [comment]
Would love to see this in GLM. This would improve my workflow a lot as it wouldn't require me to maintain my own fork of GLM anymore.

**Comment by Groovounet** [comment]
GLM uses CMake to have a single build system so if one day BUCK turns out to be more used than CMake, why not but in the meantime. I think it should remain a separate project.

Thanks,
Christophe

**Pull request closed without merging**
