### PR TITLE
Simd improvement

### PR DESCRIPTION
**Pull request by laurentcau**
- Add simd aligned_vec3 (and sse aligned_dvec3 - 2 x xmm)
- Fast packed_vec3 <=> aligned_vec3 and packed_vec4 <=> aligned_vec4 conversion
- Fast aligned_vec3 <=> aligned_vec4 conversion
- Optimized aligned_mat x aligned_mat and aligned_mat x aligned_vec
- Inverse aligned_mat3 simd version (actually slower than ssid on my computer even it has 30% less instruction ?)

### CODE REVIEW

**Comment by laurentcau** [comment]
Note: I fixed the integer div issue reported there: https://github.com/g-truc/glm/issues/1255
I also added a test to check there will be no regression in the future.
For the template issues with GLM_FORCE_NEON, since there is no detail, I can't fix it.
All tests are compiling fine on my side with clang + neon. So that should be something not covered by tests but what ? @dimitre

**Comment by laurentcau** [comment]
Tests passed
https://github.com/laurentcau/glm/actions/runs/8326367556
@christophe-lunarg

**Comment by christophe-lunarg** [comment]
Considering you didn't receive any answer from the ARM NEON issue after multiple query, I think it's fair to break it and have been for who that matters submit a PR.

**Comment by christophe-lunarg** [comment]
Thanks for contributing!

**Pull request merged**
