### PR TITLE
Implemented 'principle component analysis' utility in gtx

### PR DESCRIPTION
**Pull request by sgrottel**
PCA (principle component analysis) is a handy utility to analyze the spatial distribution of points. It can be used to compute object-oriented bounding boxes, arbitrary bsp-tree creation, etc. I used it in previous works together with particle data.

I maybe went a little overboard with the tests....

### CODE REVIEW

**Comment by christophe-lunarg** [comment]
Hi!

This works looks brilliant, I'll rather have PR with overboard tests than no test.

Let's see the C.I. result but otherwise, I think it's good to go!

**Comment by sgrottel** [comment]
Thanks for the feedback! First CI builds are as red as they can get. I will wait for the full batch to be completed and then look I'll into them.

**Comment by gottfriedleibniz** [comment]
Remaining CI issue(s) look like precision issues related to `GLM_TEST_FORCE_PURE` enabling `fpmath=387` for GNU compilers.

You can probably replicate this locally with `-DGLM_FORCE_CXX17 -DGLM_FORCE_PURE -std=c++17 -mfpmath=387` enabled; then using `-ffloat-store` afterwards to (hopefully) verify that hunch.

**Comment by sgrottel** [comment]
Thanks for the hint! I agree, those are precision issues. I will try to replicate it locally with your suggestions.

@christophe-lunarg if it's ok with you, I will adjust the test comparison epsilons for now, to make all tests pass. And, I will take another look at improving the numeric precision in another go. So, we can merge this one, as soon as CI is green. Ok?

**Comment by sgrottel** [comment]
All green. I think this is done.

I started a separate experiment for optimizing the test evaluation and computation numerics. Actually, from first looks, what we have here now, does not seem to bad at all. If I find real improvement potential, I will create a separate follow-up pull request.

Thank you!

**Comment by christophe-lunarg** [comment]
Thanks for contributing!

**Pull request merged**
