### PR TITLE
updated/fixed glm::operator<< implementation

### PR DESCRIPTION
**Pull request by regnirpsj**
g-truc/glm#323 made me think about the `glm::operator<<` for matrices. i realized they have been doing the wrong thing all along, especially using copy construction for `tmatRxC` from `tmatCxR` and the whole `transpose` logic for `glm::io::order_type`. this pull request contains a unified implementation where `tquat`/`tvec` and `tmat` use a generic printing function thanks to the introduction of `GLM_META_PROG_HELPERS`.
unfortunately, there are two versions, one for vectors and one for matrices, because both are indistinguishable, i.e. `Matrix<T,P>` vs. `Vector<T,P>`, as templates but use different names for access limits, i.e. `Vector<T,P>::components` vs. `Matrix<T,P>::[cols|rows]`. how about also adding `cols`/`rows` in `tquat`/`tvec`?

### CODE REVIEW

**Comment by Groovounet** [comment]
I didn't really took the time to understand why or what of this bug especially regarding the cols / rows things.

Wouldn't https://github.com/g-truc/glm/blob/master/glm/gtc/matrix_access.hpp be enough?

I much prefer to rely on extensions for behaviour that doesn't exist in GLSL.  

Also relying on GLM_META_PROG_HELPERS implies that they must be a behavior defined when isn't not used, this behavior can be an #error in the extension if this extension requires  GLM_META_PROG_HELPERS

**Comment by regnirpsj** [comment]
rows/cols: the original implementation didn't really adhere to the internal column-major format (as required by opengl/glsl specs), i.e. it just showed the wrong values for non-square matrices. basically, always using transposing transposing c'tors was a mistake on my part.

gtc/matrix_access only helps for matrices and is already used in that case. but it does not help to get compile time limits for tvec/tquat. i see two options. using GLM_META_PROG_HELPERS for tvec/tquat compile-time limits, as is done right now. or create specializations for tvec/tquat in gtc/matrix_access.inl. or did i miss something else?

**Comment by regnirpsj** [comment]
this pull request requires #491 to be merged beforehand

**Comment by Groovounet** [comment]
This issue should be fixed in master branch.

Thanks for contributing,
Christophe

**Pull request closed without merging**
