### PR TITLE
Extension for Euler angles

### PR DESCRIPTION
**Pull request by vitali-parkhomenko**
This PR adds the following:
- Creates the derived matrix from the rotation matrix about the X-, Y-, and Z-axis
- Creates the rotation matrix from the Euler angles (intrinsic rotations):
**_Proper Euler angles_** (z-x-z, x-y-x, y-z-y, z-y-z, x-z-x, y-x-y)
**_Tait–Bryan angles_** (y-z-x, z-x-y, x-z-y, z-y-x).
- Extracts the Euler angles from the rotation matrix (intrinsic rotations):
**_Proper Euler angles_** (z-x-z, x-y-x, y-z-y, z-y-z, x-z-x, y-x-y)
**_Tait–Bryan angles_** (y-z-x, z-x-y, x-z-y, z-y-x, y-x-z).
- Tests for these features

### CODE REVIEW

**Comment by Groovounet** [comment]
Would you consider adding tests for these features?

**Comment by vitali-parkhomenko** [comment]
Of course, only this will take a little bit more time.

**Comment by Groovounet** [comment]
Perfect! It would be great because otherwise features tend to just die.

Thanks!

**Comment by vitali-parkhomenko** [comment]
I added the tests for the feature. If it's okay, it's also possible to add these tests for the Euler angles feature, that is not related to this pull request, but is not covered by tests now. 
I mean, if you are satisfied with these tests, I can do it for glm::eulerAngleXYZ, glm::eulerAngleYXZ and glm::extractEulerAngleXYZ.

**Comment by recp** [comment]
May I ask properties of these euler angles;
- Tait–Bryan angles?
- Intrinsic or extrinsic rotations?

Thanks

**Comment by vitali-parkhomenko** [comment]
@recp Thanks for the questions!
- If you mean the sequences Tait–Bryan angles then in this pull request they are also present.
- Intrinsic rotations.

**Comment by recp** [comment]
Thank you for answering my questions;

It seems I implemented euler angles in reverse order in [cglm](https://github.com/recp/cglm) which makes them **extrinsic**, I'll fix that asap. This is why I asked "intrinsic or extrinsic rotations". I'll also ask to Blender group what conventions they use.

I think the rotation conventions must present in documentation to help others

**Comment by Groovounet** [comment]
Thanks for contributing!

**Pull request merged**
