### PR TITLE
Add targets make install and make uninstall

### PR DESCRIPTION
**Pull request by jaimedelreyg**
Add install and uninstall targets in cmake to ease installation process.

I have added the uninstall target and related files and I have set the install rules for glm's header only lib, static and shared libs.

### CODE REVIEW

**Comment by christophe-lunarg** [comment]
Hi!
Did you see https://github.com/g-truc/glm/pull/1054 PR? What made you create another PR? Are you seeing any issue?

**Comment by jaimedelreyg** [comment]
> Hi!
> Did you see #1054 PR? What made you create another PR? Are you seeing any issue?

Hi! I didn't see #1054. Sorry.

**Comment by podsvirov** [comment]
The installation of CMake and pkg-config packages was previously supported, but has been removed [here](https://github.com/g-truc/glm/commit/5f352ecce21bb1ab37fa56fac0f383c779b351a3).

**Comment by jaimedelreyg** [comment]
> The installation of CMake and pkg-config packages was previously supported, but has been removed [here](https://github.com/g-truc/glm/commit/5f352ecce21bb1ab37fa56fac0f383c779b351a3).

But why? I had to copy manually the libs and include files to use the library :(

**Comment by christophe-lunarg** [comment]
Only because it had issues that I couldn't handle or judge what to do with them.

**Pull request closed without merging**
