### PR TITLE
'if constexpr' warning (c++17)

### PR DESCRIPTION
**Pull request by timmmeh**
Adds 'if constexpr' to conditional constant expressions.
Removes warning: conditional expression is constant, consider using 'if constexpr' statement instead

### CODE REVIEW

**Comment by timmmeh** [comment]
Updated enable 'if constexpr' when c++17 is enabled.

**Comment by Groovounet** [comment]
Thanks for contributing!

**Comment by taketwo** [comment]
This condition enables `if constexpr`  for GCC7 and above, irrespective of the C++ standard actually used:

```
# elif (GLM_COMPILER & GLM_COMPILER_GCC) 
#	define GLM_HAS_IF_CONSTEXPR GLM_COMPILER >= GLM_COMPILER_GCC7
```

As a result, compilation with GCC7 in C++11 mode fails. What's the reason to have this condition? It does not make sense to me.

**Comment by timmmeh** [comment]
Looks like the issue was resolved in #922

**Pull request merged**
