### PR TITLE
README: s/aliaing/aliasing

### PR DESCRIPTION
**Pull request by dcousens**

### CODE REVIEW

**Comment by Groovounet** [comment]
Thanks for contributing,
Christophe

**Comment by dcousens** [comment]
Hi @Groovounet,  sorry if this was taken the wrong way?  Just saw it and figured I'd fix it.  I guess not?

**Comment by Groovounet** [comment]
Hi,
No no it was all good.

**Comment by Groovounet** [comment]
oupsi! Wrong button. Fixed.

**Pull request closed without merging**
