### PR TITLE
GLM bumps to version 1.0.0

### PR DESCRIPTION
**Pull request by christophe-lunarg**

### CODE REVIEW

**Comment by xiaozhuai** [comment]
Hello @christophe-lunarg 

Just remind that we should fix https://github.com/g-truc/glm/pull/1069#issuecomment-1770536163 before release 1.0.0. Otherwise it will break many downstream project.

**Comment by christophe-lunarg** [comment]
> Hello @christophe-lunarg
> 
> Just remind that we should fix [#1069 (comment)](https://github.com/g-truc/glm/pull/1069#issuecomment-1770536163) before release 1.0.0. Otherwise it will break many downstream project.
> 
> I'm looking forward to the 1.0.0 rreleas.

Please review \o/
https://github.com/g-truc/glm/pull/1183

**Comment by gottfriedleibniz** [comment]
Would there be any benefit to reopening the Issues section on Github? There are plenty of problems that have been lost in PR comment sections over the years. I think it would be nice to have a place to collect/organize these things.

**Comment by christophe-lunarg** [comment]
> Would there be any benefit to reopening the Issues section on Github? There are plenty of problems that have been reported and lost in PR comment sections over the years. I think it would be nice to have a place to collect/organize these things.

I think I still prefer that people contribute PR instead of issues to reduce the maintenance effort of the project.

**Comment by gottfriedleibniz** [comment]
I understand your perspective. It just makes it harder to [track](https://github.com/g-truc/glm/pull/1159#issuecomment-1866307229) known [bugs](https://github.com/g-truc/glm/pull/1115#issuecomment-1857655067).

**Pull request merged**
