### PR TITLE
Re-add the glm interface library in cmake

### PR DESCRIPTION
**Pull request by kiroma**
Also re-work the main cmakelists to make the project more easily embeddable

### CODE REVIEW

**Comment by Groovounet** [comment]
I am not getting the purpose of these changes... GLM doesn't need to be linked to be used.

What these interfaces library does?

**Comment by kiroma** [comment]
```cmake
add_library(dummy INTERFACE)
target_include_directories(dummy INTERFACE my_include_dir)
add_executable(my_executable main.cpp)
target_link_libraries(my_executable dummy)
```
The `INTERFACE` keyword means that when another target links against `dummy`, it must also have the includes specified for `dummy`, therefore it's about an equivalent of saying `target_include_directories(my_executable PRIVATE my_include_dir)`

**Comment by fuzzyTew** [comment]
@kiroma it doesn't look like people are successfully able to use this (see linked issue).  Are you able to give a quick description of how embedding is expected to work now?

**Comment by kiroma** [comment]
Oh god I have not looked at this in forever. I thought someone else would pick it up.
A FindGLM.cmake module has to be written. I'll take a look and see what I can come up with.

**Pull request merged**
