### PR TITLE
Static constants

### LINKED ISSUE #21: [feat.request] Add static X_POS, X_NEG,... vec3's
Unless I'm mistaken, each time you want to create an "up" vector, you have to write glm::vec(0.0f, 1.0f, 0.0f);

Ogre provides static vectors : https://bitbucket.org/sinbad/ogre/src/3cbd67467fab/OgreMain/src/OgreVector3.cpp?at=default

Unity too : http://docs.unity3d.com/Documentation/ScriptReference/Vector3-up.html (but the "forward" and "right" words are a bit confusing)

Can GLM provide similar functionality ?

### LINKED ISSUE #410: Add static unit vectors/identity matrix constants
Yeah, it's true that you could just use `something = vec4(0,0,1,0)`, but I think `something = vec4::Z` (where `Z` is `static const glm::vec4::Z {0, 0, 1, 0}` or something) would be convenient.

### PR DESCRIPTION
**Pull request by JesseTG**
Fix #21
Fix #410

### CODE REVIEW

**Comment by Groovounet** [comment]
It looks great but I think such feature should be hidden into a define (GLM_STATIC_CONSTANT_MEMBERS?) for two reasons:
- GLSL doesn't have such constants and being close to GLSL is a major design goal of the library to avoid any learning curve.
- X, Y, XYZW, etc is a potential huge source of conflicts with code base that defines ridiculous macros. I learn that years ago while working on an implementation of swizzle operators. 

Outside that, the pull request is great.

Thanks for contributing,
Christophe

**Comment by JesseTG** [comment]
Ok, I'll put it into a `#define`.

> X, Y, XYZW, etc is a potential huge source of conflicts with code base that defines ridiculous macros. I learn that years ago while working on an implementation of swizzle operators.

What would you suggest I name them, then?

**Comment by Groovounet** [comment]
I think it's good names and hidden in the define there is no chance that some users hit some strange compilation errors by accident.

**Comment by JesseTG** [comment]
Ask and you shall receive.  Merge away.

**Comment by Groovounet** [comment]
Thanks for contributing!

**Comment by JesseTG** [comment]
:thumbsup:

**Comment by Groovounet** [comment]
The pull request doesn't compile, so reverting.
https://drone.io/github.com/g-truc/glm/133

Please add some tests too.

Thanks,
Christophe

**Comment by JesseTG** [comment]
Fuck.  Okay, I'll rename those template parameters.

**Pull request merged**
