### PR TITLE
Make matrices operators constexpr

### PR DESCRIPTION
**Pull request by LucasChollet**

### CODE REVIEW

**Comment by LucasChollet** [comment]
Rebased after #1113 was merged.
@christophe-lunarg, can you have a look at this please?

**Comment by christophe-lunarg** [comment]
Hi !
Sorry for the very late reply... It would be nice for you to rebase this PR against master to get C.I. (which is fully working again!) running and testing this PR.
Thanks!

**Comment by LucasChollet** [comment]
Hi,
I just rebased it, but it doesn't seem to have triggered any CI.

**Comment by christophe-lunarg** [comment]
> Hi, I just rebased it, but it doesn't seem to have triggered any CI.

Very weird... but maybe I left the master in a bad state.... not sure. I tried stuff (TM) without success. I just tried with current master and things seem to work... Would you mind trying the rebase again? And if that doesn't work maybe creating a new pull request from the same branch?

Thanks!

**Comment by christophe-lunarg** [comment]
I created a new PR https://github.com/g-truc/glm/pull/1185 to run the unit tests. Thanks for contributing!

**Pull request closed without merging**
