### PR TITLE
Add missing cols/rows constants

### PR DESCRIPTION
**Pull request by JesseTG**
Should I add anything like `rows` or `cols` to the vector type traits?  Because they can be treated as either column vectors or row vectors, so I dunno...

### CODE REVIEW

**Comment by regnirpsj** [comment]
i vote yes, then #441 can be unified (instead of separate handling for vector and matrix).

**Comment by JesseTG** [comment]
But as row vectors or column vectors?

**Comment by regnirpsj** [comment]
iirc, they should be column vectors by default, i.e. vec4 is a mat1x4.

**Comment by JesseTG** [comment]
Actually, the spec says that it depends on whether the vector is the left or right operand in a vector/matrix multiplication.  Nowhere does it otherwise refer to the notion of a row vector or column vector.

**Comment by regnirpsj** [comment]
that is correct in a general sense but given `p' = P * V * M * p` would be the usual way in opengl to transform a point, vectors would be assumed to be column oriented; this could/should be documented. the alternative is to just stick with the `type<>::columns` and not assign col/row dimensions for non-matrices.

**Comment by JesseTG** [comment]
Let's see what @Groovounet has to say.

**Comment by JesseTG** [comment]
...so what *do* you have to say, @Groovounet?  I'm fine with the metaprogramming stuff being moved to a separate file, but until this PR is merged in I can't pull in the latest GLM changes.

**Comment by JesseTG** [comment]
Notice me, senpai~

**Comment by JesseTG** [comment]
@Groovounet Can you take a look at this bugfix, please?

**Comment by JesseTG** [comment]
@Groovounet Hi.  Do you like this change set?

**Comment by Groovounet** [comment]
I made a branch today type_trait where I investigated. Somehow there are build errors with Visual Studio.

**Comment by JesseTG** [comment]
Seriously?  Christ.  I'll take a look over the weekend.

**Comment by Groovounet** [comment]
For your information, it was already broken before your changes. I came up with a workaround (in the branch) but I don't know whether it is good.

**Comment by JesseTG** [comment]
All right, thank you for taking a look at this pull request.

**Pull request merged**
