### PR TITLE
Move header files from /glm to /include/glm subfolder

### PR DESCRIPTION
**Pull request by mknejp**
This makes it safer to include GLM as sources instead of install. By not
having the repository root as the header search path, but a dedicated
subfolder instead, chances of name clashes are reduced and the amount of
options displayed in IDEs is vastly reduced and disambiguated.

This change should not affect anyone relying on CMake's automatic
header search path setting of target dependencies. A re-run of cmake
may be necessary if it doesn't automatically pickup the changes. Already
installed/exported packages should not be affected.

Those already building from sources and managing search paths manually
need to switch from `path/to/glm` to `path/to/glm/include`.

### CODE REVIEW

**Comment by Groovounet** [comment]
I think this PR breaks all the unit tests. Also, it's a application breaking change but I don't really see how it's safer and it seem to be the only argument on the favour of this PR. I am very inclined to reject this PR...

**Comment by mknejp** [comment]
I ran all tests with the changes and they passed.

Applications that rely on CMake to wire all the header paths together should not be affected since CMake detects the change in the main CMakeLists.txt and reconfigures the project. Applications using installed packages aren't affected at all since the install destination remains the same.

Maybe it's really just a case of inconvenience but typing in `#include <util/` or `#include <test/` and getting all the wrong answers is very frustrating. This change restricts the search options to find only what actually matters.

**Comment by mknejp** [comment]
Btw I did have to call `cmake .` once in CMake's build directory after updating to get everything working so it may not be a completely transparent change and I understand if you reject this. Considering you are aiming for a 1.0 version this may be something to consider at that point since I wouldn't expect compatibility issues to be controversial in a major version change.

**Comment by JesseTG** [comment]
Yeah, this does seem like something best suited for GLM 1.0.

**Pull request closed without merging**
