### PR TITLE
Update for Conan recipe and test_package

### PR DESCRIPTION
**Pull request by danimtb**
This PR updates Conan package files for this library.

I have deleted and updated the recipe and fixed `test_package` to use new features of Conan 1.0.

However, I have seen some issues with the recipe:
- There was no "fixed" version number inside the recipe, so I added what I supossed is the latest one.
- Following the above issue it would be nice to have just one tiny CI job to perform the generation of packages for every release. As this is a header-only library it would be quite easy to do and it could only be fired whenever a new version is tagged.

If you would like me to help with CI job setup I will be happy to contribute that to the project.
Cheers!

cc/ @dimi309

### CODE REVIEW

**Comment by dimi309** [comment]
Hi @danimtb,
I think that these are good modifications. The only thing I am not too sure about is the version. The deal so far was that I maintain the conan packaging code and also make the releases on bintray. The version is "master" so that it is always relevant regardless of each release, for which it can just be temporarily modified the last minute before packaging with conan. Checking in a fixed version would require a pull request, many times after @Groovounet  has tagged a release, which I don't think is sustainable (and he told me he doesn't like modifying released versions 😄 ) Of course, if you guys figure out a more efficient way of collaboration, and even if you would like to take over the maintenance of the conan package, I have no objection at all. Just let me know 😉 Btw please note that I don't have rights to accept your pull request myself. I just thought I should give this feedback since you are referring to the conan packaging part.

**Comment by danimtb** [comment]
Hi @dimi309 
Thank you so much for your fast reply.

I see your concern about the version but I would like to propose the idea of setting the version automatically in the CI with ConanPackageTools when there is a new tag. You can see a good example of that [here](https://github.com/Blosc/c-blosc/blob/master/build.py).

That way you wouldn't have to care about manually generating packages every new release. We are happy to help improve the support of conan in this package but I think is better to keep this under the responsability of the great community with contributors like you.

I know you have no permissions in this repo but I saw you were the right person to ping for feedback in this PR 😉 

Please @Groovounet tell us what you think about the propesed flow for the CI

**Comment by dimi309** [comment]
It all sounds pretty good as far as I'm concerned. I don't know if @Groovounet would like to incorporate this into his CI (he already has one in place from what I see). If not, you could create a permanent fork I suppose. I had avoided doing so, by not writing any CI configuration and just checking all my changes back to this repository, but I do see the benefits.

**Comment by danimtb** [comment]
Any update on this @Groovounet?

**Pull request closed without merging**
