### PR TITLE
Add GLM_NOEXCEPT to a lot of functions

### PR DESCRIPTION
**Pull request by JesseTG**
Not done yet, though; still got some left to add before you merge this in

### CODE REVIEW

**Comment by Groovounet** [comment]
Did you check that this had any affect on some compiler with GLM code? 

I looked at the ASM generated code of Visual Studio 2015, exception enabled and noexcept have no effect with GLM code.

**Comment by JesseTG** [comment]
Admittedly, no, I did not.

**Comment by muep** [comment]
At least 05a347398ce7098ff616d4325fe150e7f673179a does not seem to detect absence of noexcept on gcc when building in c++98 mode. I.e. on GNU/Linux, this can be reproduced by doing just this:

``` bash
mkdir build
cd build
cmake -DGLM_TEST_ENABLE=ON ..
make
```
I can provide an exact build log later if you need it.

**Comment by JesseTG** [comment]
Probably should've put a bit more discussion into this before doing it, huh?

Want me to finish the job, or do you not think it's worth it?

Also, what about the IO module?  The standard library's `ostream::operator<<` and `istream::operator>>` aren't necessarily `noexcept`.

**Comment by Groovounet** [comment]
Some literature seems to say that using noexcept everywhere a function may not throw is a good idea:
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#S-???
F.6: If your function may not throw, declare it noexcept

So, it's go ahead with this! :)

**Comment by JesseTG** [comment]
Will do.  I'll let you know when it's ready.

**Comment by JesseTG** [comment]
Crap, I let this sit for too long.

**Pull request closed without merging**
