### PR TITLE
Is it time for version 0.10.0 ?

### PR DESCRIPTION
**Pull request by paulharris**
I see a lot of merging activity going on recently,
maybe it is time to finally tag 0.10.0 ?
It will allow packaging managers (debian, conan, etc) to release a new version...

The readme needs filling out, and does the version number need to be bumped semver-style?
ie perhaps it should at least become 0.10.0, not just adjusting the 4th item in the version number.

ie 1.x.x = breaking changes
0.10.0 = new features, no breaking changes
0.9.10 = just bugfixes, no new features

I see new features, such as the scalar_reciprocal.hpp work,
would that warrant a bump in the minor version number?

The doxy docs would also need to be regenerated,
and perhaps there are a few more PRs that could be merged before 0.10.0.

### CODE REVIEW

**Comment by tomix1024** [comment]
I think the current version 0.9.9.9 is just a result of not wanting double digit version numbers because it would interfere with the definition of the (GLM_VERSION macro](https://github.com/g-truc/glm/blob/cc98465e3508535ba8c7f6208df934c156a018dc/glm/detail/setup.hpp#L10).
Instead I would suggest adopting a macro in lieu of [VK_MAKE_VERSION(major, minor, patch)](https://github.com/KhronosGroup/Vulkan-Headers/blob/16847a61009f23b73b6de658a64e42926efc1ea9/include/vulkan/vulkan_core.h#L62)

If I look at the changelog of glm, I have the impression that glm currently does not adhere to the [semantic versioning rules](https://semver.org/) that you suggest above.

My personal preference would be to bump the glm version to 1.0.0, remove deprecated features (which do exist), change the "integer" version counter of glm to work like that of vulkan and adhere to the [semantic versioning rules](https://semver.org/) in the future.

**Comment by paulharris** [comment]
Sounds like a good plan to me (as only a project outsider though)

**Comment by Tanishq-Banyal** [comment]
I know this is unrelated but, why is glm::dot returning a vector instead of float ?

**Comment by tomix1024** [comment]
@paulharris I'm also an "outsider", but use it a lot...
Do you know if it is possible for me to contribute to your PR or should I open my own? (I think this would be unneccessarily redundant?)

@Tanishq-Banyal well, its not.
https://github.com/g-truc/glm/blob/cc98465e3508535ba8c7f6208df934c156a018dc/glm/geometric.hpp#L50

**Comment by Tanishq-Banyal** [comment]
> @Tanishq-Banyal well, its not.
> https://github.com/g-truc/glm/blob/cc98465e3508535ba8c7f6208df934c156a018dc/glm/geometric.hpp#L50
> 

It does, [this overload](https://github.com/g-truc/glm/blob/master/glm/detail/func_geometric.inl#L160) is selected by default with both arguments of type `glm::vec3`

**Comment by paulharris** [comment]
> @paulharris I'm also an "outsider", but use it a lot... Do you know if it is possible for me to contribute to your PR or should I open my own? (I think this would be unneccessarily redundant?)
> 
> @Tanishq-Banyal well, its not.
> 
> https://github.com/g-truc/glm/blob/cc98465e3508535ba8c7f6208df934c156a018dc/glm/geometric.hpp#L50

uuh it'll probably be easier if you just start your own PR.
You are welcome to bring in my changes, but more likely it'll be better if you start from scratch.
My changes are trivial...

Mention this PR in yours, and I'll close mine.

But, I'd suggest you make a non-breaking release if possible, and then a breaking 1.x release.
That way current users have something updated and stable to use while transitioning.

**Comment by tomix1024** [comment]
My current understanding is that 0.9.9.9 is not yet released, but still work in progress.
So we would just release 0.9.9.9 with the current changes.
And then could move to 1.0.0.

**Comment by christophe-lunarg** [comment]
This issue is being resolved by https://github.com/g-truc/glm/pull/1180

If you have more further feedback, there are welcome, hopefully releasing a new version of GLM soon !

**Pull request closed without merging**
