### PR TITLE
Microoptimize quatLookAt

### PR DESCRIPTION
**Pull request by stfx**

### CODE REVIEW

**Comment by Groovounet** [comment]
Hi,

Just looking at the change I can see what makes this a microoptimization. What's the reasoning behind these changes? And maybe are are the proof it's actually doing the expected improvement?

**Comment by stfx** [comment]
Unfortunately I do not have tests available right now but it would be good if this library would have base tests to check for performance improvements. Due to that I partly reverted the change to make the code fit with the existing code style and make smaller more obvious improvements to `quatLookAtLH`

**Comment by Groovounet** [comment]
Well, if you want to make performance improvements you can add performance tests.

https://github.com/g-truc/glm/blob/master/test/gtc/gtc_bitfield.cpp is a good example showing how it's done in GLM.

Thanks,
Christophe

**Comment by stfx** [comment]
I see thanks for pointing me towards those tests. Can you please let me know why the revised changes were not accepted though?

**Pull request closed without merging**
