### PR TITLE
Create an install and package targets in cmake tree

### PR DESCRIPTION
**Pull request by kiroma**
This PR should hopefully clear up some of the confusion about how CMake should be finding GLM.
It should also make it easier for package maintainers with the packages being generated by CPack.

CMake should now be able to use its internal templates to generate appropriate `glmConfig.cmake` and `glmConfigVersion.cmake` files. Those files should be installed by the `install` target, as well as included in the CPack packages.

### CODE REVIEW

**Comment by kiroma** [comment]
I believe CI will have to be adjusted to install glm somewhere and run the `tests/cmake` test based on that install dir instead of the `cmake/glm` modules

**Comment by christophe-lunarg** [comment]
This PR looks pretty good to me but I can't say I know how "install" and CPack is actually working.

It would be great that someone else review this PR.

**Comment by podsvirov** [comment]
It works and it is better than nothing.
On the other hand, I still don't understand why it was to remove the existing [functionality](https://github.com/g-truc/glm/commit/5f352ecce21bb1ab37fa56fac0f383c779b351a3)...

**Comment by christophe-lunarg** [comment]
This PR looks a lot simpler than what was used before but I can't judge. 

If you guys @kiroma @podsvirov and @jaimedelreyg could figure out together a good solution, maybe including "uninstall", that would be great

**Comment by christophe-lunarg** [comment]
In this PR I appreciate particularly that the documentation was updated and C.I. included.

**Comment by jaimedelreyg** [comment]
I can include the uninstall target :)

**Comment by jaimedelreyg** [comment]
I can include the uninstall target 👍. And I will close the duplicate issue anyway, here we can discuss the solution. This PR is great because also adds the cmake's export functionality. Also as you mention @christophe-lunarg the documentation is updated.

**Comment by christophe-lunarg** [comment]
Great!

**Comment by jaimedelreyg** [comment]
I have added a PR with the uninstallation target to @kiroma's repo kiroma/glm#1. I have needed to re-add the cmake/ folder in order to store the cmake_uninstall.cmake file as CMake's wiki mention [here](https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/recipe/AddUninstallTarget).

**Comment by christophe-lunarg** [comment]
Thanks for contributing!

**Pull request merged**
