### PR TITLE
Fix CMake FetchContent usage

### PR DESCRIPTION
**Pull request by tksuoran**
This fixes using glm via CMake FetchContent for me.

### CODE REVIEW

**Comment by Wunkolo** [comment]
I ran into issues with this too after updating GLM. I use GLM as part of my cmake project(via `add_subdirectory()`) and this is giving me trouble:
https://github.com/g-truc/glm/blob/ace16e47780dcef815294715237f51e9129b6eb3/glm/CMakeLists.txt#L49-L52

`${CMAKE_SOURCE_DIR}` resolves into the top-level project directory rather than GLM's own directory(The same folder as `MyProject/CMakeLists.txt` rather than the same folder as `MyProject/extern/glm/CMakeLists.txt`) and breaks my project with `Cannot open include file: 'glm/glm.hpp'` errors.

Hope this gets merged soon.

**Comment by sasq64** [comment]
This PR needs to be merged. GLM can not be used as a normal cmake sub_directory as intended without it.

**Comment by Wunkolo** [comment]
Yes. GLM is currently broken without this. It has been over 15 days of being broken.

**Review by kiroma — APPROVED** [review]

**Comment by JohnnyonFlame** [comment]
This issue also currently affects me, any hopes of seeing this PR merged soon or are there bigger plans for the CMake infrastructure here?

**Comment by christophe-lunarg** [comment]
Thanks for contributing and thanks to everyone for saying it's a relevant fix!

**Pull request merged**
