### PR TITLE
Add support for C++20 modules.

### PR DESCRIPTION
**Pull request by YaaZ**
Allows users to use GLM as a module. All usual options, like `GLM_ENABLE_EXPERIMENTAL`, `GLM_FORCE_INTRINSICS`, `GLM_FORCE_ALIGNED_GENTYPES`, etc can be specified via compiler options when building the module.
Notable changes:
- Exposed API is split into separate namespaces: `glm`, `glm::gtc`, `glm::ext`, `glm::gtx`. When necessary, extension namespaces can be inlined into `glm` using `GLM_***_INLINE_NAMESPACE`.
- Some missing extensions added to `ext.hpp`
- Small refactoring to get rid of internal namespaces getting in the way.

### CODE REVIEW

**Comment by christophe-lunarg** [comment]
Hi @YaaZ !
Could you rebase with master your branch and add a test using the C++20 module?

**Comment by christophe-lunarg** [comment]
This issue was resolved with https://github.com/g-truc/glm/pull/1208 which I created to rebae and run the tests.
It would be great to create a unit test otherwise the modules will be broken sooner rather than later.

Thanks!

**Comment by stripe2933** [comment]
How can I use the module feature in CMake 3.28? Can it be used like below?

```cmake
add_library(glm_module)
target_sources(glm_module PUBLIC
    FILE_SET CXX_MODULES
    FILES ${GLM_INCLUDE_DIR}/glm.cppm
)
target_link_libraries(my_project PRIVATE glm_module)
```

Or it gives some CMake option to enable the module feature by default?

**Comment by innochenti** [comment]
I'm having following errors: error C2039: 'inverseTranspose': is not a member of 'glm'

**Comment by gottfriedleibniz** [comment]
> I'm having following errors: error C2039: 'inverseTranspose': is not a member of 'glm'

Ensure you are compiling with `GLM_GTC_INLINE_NAMESPACE` defined when compiling the module to inline the namespace. Otherwise fully qualify with `glm::gtc::inverseTranspose`

**Comment by theoparis** [comment]
> How can I use the module feature in CMake 3.28? Can it be used like below?
> 
> ```cmake
> add_library(glm_module)
> target_sources(glm_module PUBLIC
>     FILE_SET CXX_MODULES
>     FILES ${GLM_INCLUDE_DIR}/glm.cppm
> )
> target_link_libraries(my_project PRIVATE glm_module)
> ```
> 
> Or it gives some CMake option to enable the module feature by default?

+1 for this, I don't see a cmake option to build and install glm.cppm.

**Pull request closed without merging**
