### PR TITLE
Proposal for major version upgrade

### PR DESCRIPTION
**Pull request by tomix1024**
Hi, as already discussed with @paulharris in #1108 I would suggest that we increase the version of glm to 1.0.0.
I think the current situation of having a version number 0.9.9.9, and not really being able to increase it any further, is just a result of not being able to handle double-digit version numbers because it would interfere with the definition of the [GLM_VERSION macro](https://github.com/g-truc/glm/blob/cc98465e3508535ba8c7f6208df934c156a018dc/glm/detail/setup.hpp#L10).
Instead I would suggest adopting a macro in lieu of [VK_MAKE_API_VERSION(major, minor, patch)](https://github.com/KhronosGroup/Vulkan-Headers/blob/16847a61009f23b73b6de658a64e42926efc1ea9/include/vulkan/vulkan_core.h#L68).
This would give us room for 1024 minor versions and 4096 patch versions before running out of space in the version number ;)

For future updates, I would suggest adhering to the [semantic versioning rules](https://semver.org/):
> MAJOR version when you make incompatible API changes
> MINOR version when you add functionality in a backwards compatible manner
> PATCH version when you make backwards compatible bug fixes

Therefore I have included the removal of features marked as deprecated in this PR.

### CODE REVIEW

**Comment by christophe-lunarg** [comment]
Note that version 0.9.9.9 is officially not released...
The main issue is that some C.I. infrastructures has ceased, I think I would need to change all this to Github actions... but I am open to others systems...

This is a necessary step to ensure all the tests build and run on all main compilers recents to pretty old versions.

I thinks with version 1.0.0 we could also bump the minimum compiler requirements, maybe even require C++11?

**Comment by xiaozhuai** [comment]
@christophe-lunarg 
Hi there.
Any progress of a new release?
See also https://github.com/microsoft/vcpkg/pull/32685

**Comment by maidenone** [comment]
Would just like to point out that gaussRand is off?

image

**Comment by gottfriedleibniz** [comment]
> Would just like to point out that gaussRand is off?

I believe [gaussRand](https://github.com/g-truc/glm/blob/master/glm/gtc/random.inl#L219-L231) should be implementing the [Marsaglia polar method](https://en.wikipedia.org/wiki/Marsaglia_polar_method). ... It does look a little off.

**Comment by christophe-lunarg** [comment]
This issue is being resolved by https://github.com/g-truc/glm/pull/1180 and I took inspiration of the proposed changes in this PR.

If you have more further feedback, there are welcome, hopefully releasing a new version of GLM soon !

**Pull request closed without merging**
