### PR TITLE
Add constructors to aid in meta-programming

### PR DESCRIPTION
**Pull request by JesseTG**
In a project of mine, I need to be able to have functions that convert between all the different vector types at will (and matrices, and quaternions).  I do *not* feel like writing 225 different functions (`vec2`, `vec3`, and `vec4`, times the 5 instantiations I care about) to do this.  I managed to make it work with templates, but [it's not pretty](https://github.com/JesseTG/BALLS/blob/master/BALLS/BALLS/util/MetaTypeConverters.cpp).  If I could just use one constructor interface for each vector type, it would make things much easier on me.  So I did.

### CODE REVIEW

**Comment by Groovounet** [comment]
I don't think that accumulating option is a solution for GLM as this is growing in too much complexity. 

If you really need such functionality for metaprogramming purposes, you should be able to write code outside GLM to produce the same behavior.

Thanks,
Christophe

**Comment by JesseTG** [comment]
What would you suggest, then?

**Comment by Groovounet** [comment]
template <typename T, precision P, template <typename, precision> class vecType>
vecType<T, P> make_vec(T x, T y, T z, Tw);

?

**Comment by JesseTG** [comment]
I'll look to see if doing so will make my code smaller.

**Pull request closed without merging**
